site_name: Довідник Пайтон
site_url: https://localhost:8000/ekids
theme:
  logo: assets/logo.png
  name: material
  language: uk
  font:
    text: Source Sans 3
    code: Source Code Pro
  features:
    - search.suggest
    - search.highlight
  palette:

    # scheme: youtube

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Світла

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: lime
      toggle:
        icon: material/weather-sunny 
        name: Темна

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Автоматична

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# plugins:
#   - offline
#   - search